# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# ネストが深すぎる
BlockNesting:
  Max: 5

# クラスの行数が多すぎる
ClassLength:
  Enabled: false

# 例外を抑制している
SuppressedException:
  Enabled: false

# 行が長すぎる
LineLength:
  Enabled: false

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 引数の数が多すぎる
ParameterLists:
  Max: 12

# Offense count: 1
Metrics/AbcSize:
  Enabled: false

# Offense count: 1
Metrics/CyclomaticComplexity:
  Enabled: false

# Offense count: 1
Metrics/PerceivedComplexity:
  Enabled: false
